#!/usr/bin/env bash
# This script is displaying "bad luck" on the 4th iter, "good luck" on the 8th iter,
# and "Holberton School" otherwise for 10 iterations
counter=0
while  [ $counter -le 9 ]
do
	counter=$(( counter + 1))
	if [ $counter == 4 ]
	then
		echo 'bad luck'
	elif [ $counter == 8 ]
	then
		echo 'good luck'
	else
		echo 'Holberton School'
	fi
done
