#!/usr/bin/env bash
# This script is displaying "bad luck from China" on the 4th iter,
# "bad luck from Japan" on the 9th iter, "bad luck from Italy on the 17th iter
# and the iteration number otherwise for 20 iterations
counter=0
while  [ $counter -le 19 ]; do
	counter=$(( counter + 1))
	case $counter in
		4)
			echo $counter;
			echo 'bad luck from China';;
		9)
			echo $counter;
			echo 'bad luck from Japan';;
		17)
			echo $counter;
			echo 'bad luck from Italy';;
		*)
			echo $counter;
	esac
done
