#!/usr/bin/env bash
# This script is displaying information about the holbertonschool file
file="holbertonschool"
if [ ! -e "$file" ]; then
	echo 'holbertonschool file does not exist'
elif [ -f "$file" ] && [[ ! -s "$file" ]]; then
	echo 'holbertonschool file exists'
	echo 'holbertonschool file is empty'
elif [ -f "$file" ] && [[ -s "$file" ]]; then
	echo 'holbertonschool file exists'
	echo 'holbertonschool file is not empty'
elif [ -d "$file" ] && [[ -s "$file" ]]; then
	echo 'holbertonschool file exists'
	echo 'holbertonschool file is not empty'
fi
if [ -f "$file" ]; then
	echo 'holbertonschool is a regular file'
else
	:
fi
