#!/usr/bin/env bash
# A script that transfers a file from our client to a server
if [ $# -ne 3 ]; then
	echo Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
	exit 1
fi

export PATH_TO_FILE=$1
export IP=$2
export USERNAME=$3
export PATH_TO_SSH_KEY=$4

scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/ "$4"
